### PR TITLE
Add suggest section to composer.json

### PR DESCRIPTION
**Pull request by sergeyz**

### CODE REVIEW

**Comment by jkuchar** [comment]
Only downside of this is that it will give you suggestion event when you have one of those two installed. (e.g. when you have gmp it will suggests bcmath)

**Comment by BenMorel** [comment]
I would agree with @jkuchar, which is the very reason why I haven't put a `suggest` for these extensions in the first place!

**Comment by jkuchar** [comment]
Possible solution for this can be to have 3 packages with drivers, so you install what you want to use (emulation, gmp, bcmath). 

However it seems to me little like overengeneering. 
- It is just one class per "driver"
- you cannot use math package on it's own without driver
- then there can be one of those three packages suggested by math package

But to be honest I do not see any real usecase for this. Do you?

**Comment by BenMorel** [comment]
I don't, personally. It works out of the box, and if you care to read the README, you'll see the suggestion to install either GMP or BCMath. I would leave it as it is.

**Pull request closed without merging**
