### PR TITLE
Create .editorconfig

### PR DESCRIPTION
**Pull request by voyula**

### CODE REVIEW

**Comment by BenMorel** [comment]
Hi, what’s it for?

**Comment by voyula** [comment]
@BenMorel For consistent coding styles.

https://editorconfig.org/

**Comment by BenMorel** [comment]
What tools support this? I can at least see that PHPStorm has a plugin to support this.
What about other IDEs?

Are there code checking tools that can check the editorconfig coding style, and be integrated into Travis CI? Isn't this redundant with phpcs?

What do *you* use it for?

Sorry for the flood of questions, but I never came across editorconfig before, and need to make an opinion about whether this is worth adding.

**Comment by voyula** [comment]
@BenMorel 

20+ IDE/Editor, supporting EditorConfig.

This not a coding language standart linter, **not like PHPCS**.

This a coding time otomatic fixer for unnecessary spaces, charset encoding, eof, indent size etc.

**Comment by BenMorel** [comment]
Thank you. Are there popular open source projects using editorconfig?

**Comment by voyula** [comment]
@BenMorel 

https://github.com/laravel/laravel
https://github.com/symfony/symfony
https://github.com/guzzle/guzzle
https://github.com/slimphp/Slim
etc.

**Comment by BenMorel** [comment]
Thanks for the list! This looks widespread indeed.

> And GitHub is auto-fixing all commits with EditorConfig settings. Not need a 3rd party extension.

Wow. This looks surprising, as this would change the commit ID and make a mess of each push/pull. Do you have a link that would explain this?

**Comment by voyula** [comment]
@BenMorel Github will auto normalize all commits and not will new commit, because this only normalization proccess for typo and file.

**Comment by BenMorel** [comment]
...but changing a git commit contents changes its hash, so there's something wrong here.
Do you have a source for this info?

**Comment by voyula** [comment]
https://github.com/editorconfig/editorconfig.github.com/pull/48

**Comment by BenMorel** [comment]
What I understand from this thread is that GitHub may use editorconfig to normalize files **displayed in the browser** on github.com; this doesn't touch the commits themselves.

I'm surprised I can't find a GitHub doc confirming this, though.

**Comment by voyula** [comment]
Are you will accept this PR? 😀

**Comment by BenMorel** [comment]
Probably. I'm still making up my mind!

**Comment by BenMorel** [comment]
@voyula OK let's do this. Thanks for contributing!

**Comment by crstauf** [comment]
Arrived here from the PR on the `editorconfig` browser extension repository. I believe this means that if you're creating/editing a file on GitHub.com, the editor config options will be applied. Not that commits you push up will be changed.

**Comment by BenMorel** [comment]
Makes sense, @crstauf. Thanks for the clarification!

**Pull request merged**
