### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by BenMorel** [comment]
Duplicate of #52.

**Comment by reedy** [comment]
It's not really a duplicate... it's for the 0.8 branch...

**Comment by BenMorel** [comment]
Oops! I missed that. Merged as well!

**Comment by reedy** [comment]
Haha. Thanks!

When I saw master was 0.9, and you were still (at least in August) doing releases from 0.8, I thought it was worth getting the fix into both branches

**Pull request merged**
